language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
      - libsndfile1
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
install:
  - python setup.py install
  - pip install scipy
  - pip install numpy
  - pip install -r extended_requirements.txt
script:
  - py.test tests/ --cov=sigfeat/ --cov-report term-missing
after_success:
    - codecov
